### ISSUE TITLE
Připravit nový úvodní e-mail před registrací 

### ISSUE THREAD

**Issue by jakubboucek** [plzenskybarcamp/plzenskybarcamp-web#19]
- [x] Navrhnout aktuální copy
- [x] Vyřešit souhlas pro další posílání (viz #12)

**Comment by jiri-kolarik** [comment]
@jakubboucek Přístup do Mailchimpu mám.
Připravil jsem tedy nový mail - zatím v Draftu.
Zkušební kopii jsem Ti odeslal.
Na společném callu dořešíme případné vylepšení a doladění.

**Comment by jiri-kolarik** [comment]
E-mail úspěšně odeslán :)
