### ISSUE TITLE
Nasadit loga partnerů

### ISSUE THREAD

**Issue by jiri-kolarik** [plzenskybarcamp/plzenskybarcamp-web#22]
Úpravy do sekce [Partneri](https://www.plzenskybarcamp.cz/partneri)

- [x] [Eurosoftware](http://www.eurosoftware.cz/) = "**Zlataci**" + toto i na **Homepage**!
- [x] [Ecomail](https://www.ecomail.cz/) = "**Stribrnaci**"
- [x] [Shoptet](https://www.shoptet.cz/) = "**Medaci**"
- [x] [Ulozto](https://ulozto.cz/) = "**Partneri**" (je to dole az pod medakama)
- [x] [Eletur](https://www.eletur.cz/) = "**Partneri**" (pouze presuneme z medaku => do partneru)
- [x] [PlzenecNet](https://plzenec.net/) =  "**Partneri**"
- [x] [HotoFoto](https://hf-studio.cz/) =  "**Partneri**"
- [x] Arnie's =  "**Partneri**" (bez prokliku na web - nemaji)

Nová loga na [Drivu](https://drive.google.com/drive/folders/1NdmUg5oKmobSm_gbC1n35J1LdlvxCXcV?usp=sharing)

**Comment by jakubboucek** [comment]
Ostatní smazat?

Od některých (například [Uložto](https://github.com/plzenskybarcamp/plzenskybarcamp-web/blob/master/www/media/partners/ulozto-logo.png)) loga máme. Seznam všech: https://github.com/plzenskybarcamp/plzenskybarcamp-web/tree/master/www/media/partners

**Comment by jiri-kolarik** [comment]
@jakubboucek všechna původní loga (co jsou teď na webu) ZŮSTÁVAJÍ !

Shoptet a Ulozto muzeme pouzit ta, co mame.

**Comment by jiri-kolarik** [comment]
@jakubboucek prosím o nasazení partnerů - viz. zadání

**Comment by jiri-kolarik** [comment]
@jakubboucek Díky za rychlé nasazení :) jeden z pratnerů už dneska zaplatil, tak je super, že mám logo na webu.

Prosímtě, Zlaťácí - jsou tam dvě loga v nepoměru. Socialbakers je oproti Eurosoftware dost malé => mohl bys prosím velikosti sjednotit? (zvětšit SBKS, zmenšit ES, obě upravit), prostě aby měli podobnou velikost (šířku). Přeci jen jsou oba partneři na stejné úrovni. Obecně zlatí parneři mohou mít větší loga než osatní. Díky

**Comment by jakubboucek** [comment]
Ty hlavní partnery mám jak v sekci partnerů, tak na homepage, špatně zarovnané. Šlo by fixnout, prosím?

**Comment by jiri-kolarik** [comment]
@jakubboucek a ještě tenhle rest je pořád otevřený.
