### ISSUE TITLE
Problém s certifikátem / URL

### ISSUE THREAD

**Issue by jiri-kolarik** [plzenskybarcamp/plzenskybarcamp-web#31]
Pokud zadám URL adresu bez www, vyskočí chybová hláška ([screen](https://www.dropbox.com/s/ol3xbs8qxziy78r/Screenshot%202018-04-05%2007.27.12.png?dl=0)). Prosím o fix.

**Comment by jakubboucek** [comment]
Díky z upozornění. Fixed
